language: node_js
node_js:
- 'stable'
- '10'
- '9'
- '8'
- '7'
- '6'
- '5'
- '4'
before_install:
# https://github.com/npm/npm/issues/11283
- npm set progress=false
after_success: npm run coveralls
env:
  global:
    # COVERALLS_REPO_TOKEN=
      secure: "I8mDH0n2DQHAPvUFEV/ZNmrMNYTJxgywg8+P3yuCAWwQkZeXQi0DWG+6VUpOylaRhL/4kCdZK9gnJD2MfrqvNqVLDUqBK3tTmZVoyqqJEdE0UdEHcPncAPmxWrG98sDjqFN9r4nWeizHvyA1fNRQHRN56Zy+DcQWjgEhHJaYeNA="
