language: node_js
cache: yarn
node_js:
- 'stable'
- '10'
- '8'
- '6'
after_success: yarn coveralls
env:
  global:
    # COVERALLS_REPO_TOKEN=
      secure: "I8mDH0n2DQHAPvUFEV/ZNmrMNYTJxgywg8+P3yuCAWwQkZeXQi0DWG+6VUpOylaRhL/4kCdZK9gnJD2MfrqvNqVLDUqBK3tTmZVoyqqJEdE0UdEHcPncAPmxWrG98sDjqFN9r4nWeizHvyA1fNRQHRN56Zy+DcQWjgEhHJaYeNA="
